[build-system]
requires = ["scikit-build-core", "nanobind"]
build-backend = "scikit_build_core.build"

[project]
name="FunEngine"
version = "0.1.0"
requires-python = ">=3.8"

[project.optional-dependencies]
test = ["pytest"]
